[[main]]
name = "posts"
pageRef = "/posts"
weight = 10

[[main]]
name = "projects"
pageRef = "/projects"
weight = 20

[[footer]]
name = "tags"
pageRef = "/tags"
weight = 10

[[footer]]
name = "categories"
pageRef = "/categories"
weight = 20
